language: rust
rust:
  - stable
  - beta
cache: cargo
before_script:
  - rustup component add clippy
script:
  - cargo build --verbose --all
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --verbose --all
matrix:
  fast_finish: true
